---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
  - name: centos-6.7
  - name: centos-5.11
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-8.4
  - name: debian-7.9

suites:
- name: default
  run_list:
    - recipe[apt::default]
    - recipe[vsftpd::default]
  attributes:
    vsftpd:
      config:
        listen_address: 127.0.0.1
      allowed:
        - vagrant
