sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-trusty to install the stable release
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=mysql-ubuntu-1204
  - INSTANCE=mysql-ubuntu-1404
  - INSTANCE=mysql-ubuntu-1604
  - INSTANCE=mysql-centos-6
  - INSTANCE=mysql-centos-7
  - INSTANCE=postgresql-ubuntu-1204
  - INSTANCE=postgresql-ubuntu-1404
  - INSTANCE=postgresql-ubuntu-1604
  - INSTANCE=postgresql-centos-6
  - INSTANCE=postgresql-centos-7
  - INSTANCE=sqlite-ubuntu-1204
  - INSTANCE=sqlite-ubuntu-1404
  - INSTANCE=sqlite-ubuntu-1604
  - INSTANCE=sqlite-centos-6
  - INSTANCE=sqlite-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script: KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - before_script:
      - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      - /opt/chefdk/embedded/bin/chef --version
      - /opt/chefdk/embedded/bin/cookstyle --version
      - /opt/chefdk/embedded/bin/foodcritic --version
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
